### ISSUE TITLE
generate private key instead of key pair

### ISSUE THREAD

**Issue by hclarke** [mjewkes/Axolotl-Rust#21]
by having a derive_public function, and a generate_pair function, the trait implementor has to repeat the public key derivation twice.

**Comment by jazzz** [comment]
After implementing the Axolotl trait again, I might be leaning more towards keeping generate_pair and removing derive_public key. It's just more to manage on the impl side. With little or no benefit.

Thoughts?

**Comment by hclarke** [comment]
i don't see much difference. as long as there's only one way to generate a public key.
one less function to implement with your suggestion.
