### ISSUE TITLE
Plaintext should wrap a &[u8], rather than a Box<[u8]>.

### ISSUE THREAD

**Issue by jazzz** [mjewkes/Axolotl-Rust#6]
this will require changing Axolotl and AxolotlState.

**Comment by Ryman** [comment]
Not sure if this is possible currently as the associated type `PlainText` can't have a lifetime bound currently in rust. It also wouldn't be able to be returned from `decrypt` unless the decryption is in-place.

What's the motivation for wanting to wrap `&[u8]` in this case? If it's to easier access the data, then implementing `Deref<[u8]>` would help.

**Comment by hclarke** [comment]
there are two reasons:
- it should be easy to encrypt String, str, Vec<u8>, [u8;N], etc. passing in a &[u8] is an easy way to do that.
- forcing the caller to allocate memory and do a copy should be avoided if it's not actually necessary

considering removing the Plaintext associated type, and having a Plaintext<'a> struct instead. or just passing in a &[u8] to encrypt.

**Comment by hclarke** [comment]
obsolete. plaintext/ciphertext are now passed by value to allow in-place modification in encrypt/decrypt.
